### PR TITLE
Added Ansible tutorial for beginners

### PR DESCRIPTION
**Pull request by mariuszmspace**

### CODE REVIEW

**Comment by mariuszmspace** [comment]
Hey, @KeyboardInterrupt can you take a look?

**Comment by IronTooch** [comment]
@mariuszmspace Opened an issue to see if this is still being maintained, but if not, happy to accept a Pull Req at https://github.com/IronTooch/awesome-ansible

**Comment by mariuszmspace** [comment]
@IronTooch Thanks, just did a PR in your repo also:)

**Comment by KeyboardInterrupt** [comment]
Hi, I was very busy lately, But I finally found the time to check out your addition.
Looks Good, and I will gladly merge it.

**Comment by KeyboardInterrupt** [comment]
@IronTooch Hi, Sorry, for not getting back to you, yes, this Repository is still maintained, I will communicate further, in the Issue you opened.

**Pull request merged**
